/**
 * Re-exports the generated OpenAPI TypeScript client's public surface -- `IdentityApiService`,
 * `AuditApiService`, `OrganizationApiService`, every request/response model, `provideApi()`, and
 * the `Configuration`/`BASE_PATH` DI tokens -- so a consumer never imports from
 * `@ums/shared/../generated/...` directly. See `./generated/README.md` for the full generated
 * surface (auto-written by the generator) and this package's own README "Refreshing the API
 * client" for how it's produced.
 *
 * Everything under `./generated/` is committed, generator-produced code -- regenerated by
 * `npm run client:generate` from `contracts/ums-core.v1.json`, which wipes and rewrites the whole
 * directory. Never hand-edit anything in there; a manual edit is silently discarded on the next
 * regeneration.
 */
export * from './generated';
